version: "3"
services:
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devnews
      - POSTGRES_USER=devnews_user
      - POSTGRES_PASSWORD=devnews_pass
    ports:
      - "5431:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: